src/controller/Storage.java
src/controller/TestDriver.java
src/model/Auction.java
src/model/User.java

**See previous comments**
We can get started by seeing if everyone can open and execute an Eclipse file. This is setup for Java 8.
Persistent storage is working for a dummy User and Auction class. For serialization we just need to have unique serial numbers for each class, and they cannot be changed. Try to run it so we can get going!

Added comments to starter code.

---

src/model/NonProfitContact.java
src/model/NonProfitContactTest.java

makingNopProfitContactTest

---

src/JUnit/AuctionCalendarTests.java
src/JUnit/BidderTests.java
src/JUnit/BusRuleTests.java
src/model/AuctionCalendar.java
src/model/AuctionItem.java
src/model/Bid.java
src/model/Bidder.java
src/model/ItemTest.java

I added the JUnit tests for Business rules 5d and 7e.

Add JUnit tests for placing a new bid.

---

src/model/AuctionCalendar.java
src/view/DummyData.java

Merge the updated AuctionCalendar class

Add the forceAddAuctionInThePast method in the AuctionCalendar

---

src/view/NewUser.java
src/view/mainDriver.java
src/view/viewBids.java

updated view classess

---

src/view/DemoData.java

Add the DemoData

---

src/model/AuctionCalendar.java
src/model/AuctionDate.java

Fixed +1 error in auctioncallendar

Fixed +1 error in calendar and date format() problem

---

src/model/AuctionCalendar.java
src/view/DemoData.java

Add fix for the demoData to forceAddAuctions

---

src/view/ViewBidMenu.java
src/view/ViewItems.java
src/view/mainDriver.java
src/view/viewBidMenu.java

Add the viewBidMenu

---

src/model/Auction.java
src/model/Bidder.java
src/view/DummyData.java
src/view/ForceNewTestUser.java
src/view/ViewBidMenu.java
src/view/ViewItems.java
src/view/mainDriver.java
src/view/viewNonProfit.java

Updates the mainDriver to show the processBidScreen to the user

Update the mainDriver

---

src/view/ViewBidMenu.java

Add fix where a new bid was not being associated with the user correctly

Add fix for processing a new bid

---

src/view/DemoData.java
src/view/DummyData.java
src/view/ForceNewTestUser.java
src/view/ViewBids.java
src/view/ViewItems.java
src/view/auctionRequest.java
src/view/mainDriver.java

Yohei dev2

---

src/model/Auction.java
src/view/ViewBidMenu.java

fixed error with adding bid to auction twice and concurrentModException

---

src/backend/StorageIO.java
src/backend/TestDriver.java
src/model/Auction.java
src/model/AuctionCalendar.java
src/model/AuctionDate.java
src/model/AuctionManager.java
src/model/Bidder.java
src/model/Calendar.java
src/model/Manager.java
src/model/NewAuctionRequest.java
src/model/NewBidRequest.java
src/model/NewItemRequest.java
src/model/NonProfitContact.java
src/view/ViewAuction.java
src/view/ViewBidMenu.java
src/view/ViewBids.java
src/view/ViewItems.java
src/view/viewNonProfit.java

making lines under 80 characters and putting some java doc

Yohei dev3

---

src/gui/AuctionTileViewController.java
src/gui/InformationContainerViewController.java
src/gui/MenuBar.fxml
src/gui/MenuBarController.java
src/gui/MenuButton.java
src/gui/SessionController.java
src/gui/TileFactory.java
src/gui/UserView.fxml
src/gui/UserViewController.java
src/gui/ViewMenuButtonController.java
src/gui/menuBar.css
src/gui/menuBarView.css

Added the employee menu which allows us to log in as employee1 and then view all the auctions in the system.
Added the scrollPane in the gridArea where the InformationContainerView is added. This allows us to scroll when we have more several auctions to view that don't fit in the allotted width.

Add employeeMenu and scrollPane

---

src/gui/UserViewController.java

Fixed auction picker within range.

---

src/gui/NewBidFormController.java

Updated BidForm

---

src/gui/NewAuctionForm.fxml
src/gui/NewAuctionFormController.java

update the Auction request form

update new auction form request

---

src/gui/NewBidFormController.java

Adding successfully bidding comment

Adding successful coment when bidding.

---

src/gui/InformationContainerViewController.java
src/gui/ModifySystemView.fxml
src/gui/ModifySystemViewController.java
src/gui/NewBidForm.fxml
src/gui/NewBidFormController.java
src/gui/SessionController.java
src/gui/SubMenuFactory.java
src/gui/UserView.fxml
src/gui/form.css
src/gui/menuBar.css
src/model/AuctionManager.java

The new form allows an employee to change the maximum number of upcoming auctions the system is able to accept

Add the modify system form

---

src/gui/NewAuctionFormController.java

Disabled dates out of eligible range for requesting auction on

---

src/gui/NewBidFormController.java

Fixed for fraction value can be bidden.

Fixed for fraction value can be bidden.

---

src/gui/InformationContainerViewController.java
src/gui/SubMenuFactory.java

Added a control for a bidder to view all items they've bid on from all auctions
Also removed the onEnter event for a bidTile. This is done considering we don't want to give the user the impression that they can click on a bidTile to modify it

Add a showAllItems subControl for a bidder

---

src/gui/NewBidForm.fxml
src/gui/informationContainer.css
src/gui/menuBar.css

changing background color

---

src/gui/LoginView.fxml
src/gui/logging.css

Updated the CSS on the login screen so it aligns with the CSS used throughout the system. For example since in the system Helvetica is used as the main font changed the login screens use of Arial to Helvetica

Update the login screen CSS to align with the CSS used throughout
